[versions]
agp = "9.1.0-alpha01"
android-compileSdk = "36"
android-minSdk = "24"
android-targetSdk = "36"
androidx-activity = "1.12.2"
androidx-appcompat = "1.7.1"
androidx-core = "1.17.0"
androidx-espresso = "3.7.0"
androidx-lifecycle = "2.9.6"
androidx-testExt = "1.3.0"
androidx-compose-ui-tooling = "1.11.0-alpha02"
composeMultiplatform = "1.10.0-rc02"
concurrentFuturesKtx = "1.3.0"
constraintlayoutCompose = "0.6.1"
junit = "4.13.2"
kotlin = "2.3.0"
kotlin-coroutine = "1.10.2"
koin = "4.1.1"
liquid = "1.1.0"
material3 = "1.9.0"
skiko = "0.9.37.3"
startup = "1.2.0"
precompose = "1.7.0-alpha03"
litert = "2.1.0"
accompanist-permissions = "0.37.3"
camerax = "1.5.2"
atomicfu = "0.29.0"
guava = "33.0.0-android"

[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-testJunit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
junit = { module = "junit:junit", version.ref = "junit" }

# AndroidX
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-testExt-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-testExt" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-espresso" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-compose-ui-tooling = {module = "androidx.compose.ui:ui-tooling" ,version.ref="androidx-compose-ui-tooling"}
androidx-compose-ui-tooling-preview = {module = "androidx.compose.ui:ui-tooling-prteview" ,version.ref="androidx-compose-ui-tooling"}

androidx-concurrent-futures-ktx = { module = "androidx.concurrent:concurrent-futures-ktx", version.ref = "concurrentFuturesKtx" }

guava-android = { group = "com.google.guava", name = "guava", version.ref = "guava" }

androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-lifecycle-viewmodelCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtimeCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
androidx-constraintlayout-compose = { module = "tech.annexflow.compose:constraintlayout-compose-multiplatform", version.ref = "constraintlayoutCompose" }

# CMP
material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "material3" }
runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "composeMultiplatform" }

ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "composeMultiplatform" }
ui-tooling = { module = "org.jetbrains.compose.ui:ui-tooling", version.ref = "composeMultiplatform" }
ui-tooling-preview = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "composeMultiplatform" }

foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "composeMultiplatform" }

components-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "composeMultiplatform" }

# Coroutines
kotlin-coroutines = {module ="org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref ="kotlin-coroutine"}
kotlin-coroutines-android = {module="org.jetbrains.kotlinx:kotlinx-coroutines-android" ,version.ref="kotlin-coroutine"}


# Koin
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }

# Startup Runtime
androidx-startup = { module = "androidx.startup:startup-runtime", version.ref = "startup" }

# Precompose
precompose-core = { module = "moe.tlaster:precompose", version.ref = "precompose" }

# litert for Android
litertGpuApi = { module = "com.google.ai.edge.litert:litert-gpu-api", version.ref = "litert" }
litert = { module = "com.google.ai.edge.litert:litert", version.ref = "litert" }
litertGPU = { module = "com.google.ai.edge.litert:litert-gpu", version.ref = "litert" }

skiko = { module = "org.jetbrains.skiko:skiko", version.ref = "skiko" }

accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist-permissions" }

# Camerax for Android
androidx-camera = { group = "androidx.camera", name = "camera-view", version.ref = "camerax" }
androidx-camera-core = { module = "androidx.camera:camera-core", version.ref = "camerax" }
androidx-camera-lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "camerax" }
androidx-camera2 = {module = "androidx.camera:camera-camera2", version.ref = "camerax"}

atomicfu = { module = "org.jetbrains.kotlinx:atomicfu", version.ref = "atomicfu" }
liquid = { module = "io.github.fletchmckee.liquid:liquid", version.ref = "liquid" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinCocoapods = { id = "org.jetbrains.kotlin.native.cocoapods", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
androidKotlinMultiplatformLibrary = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }